#!/bin/sh

git diff-tree --no-commit-id --name-only -r HEAD~0 | grep '.md' > /dev/null

if [ "$?" = "0" ]; then
	echo "Rebulding website, please wait..."
	git stash save > /dev/null
	gulp build > /dev/null
	git status --untracked-files=no | grep 'modified' | grep -E '.html' > /dev/null

	if [ "$?" = "0" ]; then
		git add $(git status --untracked-files=no | grep 'modified' | grep -E '.html' | cut -d ':' -f 2 | tr -d ' ')
		git commit -m "Updating website."
		echo "Done."
	else
		echo "No changes."
	fi

	git stash pop > /dev/null
fi
