#!/bin/sh

git status --untracked-files=no | grep 'modified' | grep '.md' > /dev/null

if [ "$?" = "0" ]; then
	gulp build
	git add $(git status --untracked-files=no | grep 'modified' | grep -E '.md|.html' | cut -d ':' -f 2 | tr -d ' ')
	git commit -m "Updating website."
	git push
fi
